name: tekartik_app_image_web
description: Web image manipulation
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  web: '>=0.5.0'
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
  tekartik_app_image:
    git:
      url: https://github.com/tekartik/app_image.dart
      path: packages/app_image
      ref: dart3a
    version: '>=0.1.0'

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  image:
dependency_overrides:
  web: '>=1.0.0'
  tekartik_app_image:
    path: ../app_image
