name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - example/app_pick_crop_image_demo
  - packages/app_image
  - packages/app_image_web
  - packages/app_pick_crop_image_flutter
  - repo_support
