name: tekartik_app_image
description: Image definition and constants
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
    version: '>=0.13.1'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
