name: tekartik_app_image
description: Image definition and constants
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.13.2'
  image: '>=4.2.0'
  collection: ">=1.18.0"
  dev_build: ">=1.1.2"
  path: ">=1.9.0"

dev_dependencies:
  fs_shim: ">=2.3.3+1"
  lints: ">=5.0.0"
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
resolution: workspace
