name: tekartik_app_image
description: Image definition and constants
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.13.2'
  image:
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  process_run:
