name: tekartik_app_image
description: Image definition and constants
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.13.2'
  image: '>=4.0.0'
  collection:
dev_dependencies:
  lints: '>=1.0.0'
  test: '>=1.16.0'
  process_run:
  path:
