name: app_image_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.9.0

dependencies:
  process_run: ">=1.2.1+1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.13.2'
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"

dependency_overrides:
resolution: workspace
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
